In [3]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df = pd.read_csv("D:/NextLeap/Final_Project_June/instagram data.csv")

print(df.shape)
df.head()

(100000, 26)

,reel_id,creator_id,creator_followers,posting_time,reel_length_sec,hook_strength_score,caption_length,hashtags_count,trending_audio,audio_popularity_score,...,likes,comments,shares,saves,engagement_rate,impressions,reach,non_follower_reach_ratio,explore_page_boost,virality_score
0,c437715e-d1e4-4f40-8548-8718243c6516,70c2ca5a-9d3a-4ba0-9aed-62cdbbc1663f,4208388,3,31,0.451657,0,20,True,0.399659,...,779301,30002,16741,21305,0.884296,75968410,39007279,0.960121,False,82.843160
1,9097bb11-0e03-4360-a239-6613ed2025df,b6bb4240-6341-47ce-bdd4-86fcba18d9ad,4096880,4,38,0.988437,205,2,False,0.294848,...,482481,49717,10095,19802,0.609125,90722120,84132612,0.909716,False,60.256519
2,a8e09994-3314-400b-9f3a-683b494f1070,7902b14d-cb95-4673-8ef1-482ff5151801,2624351,0,13,0.019949,205,6,True,0.697575,...,925249,12046,13883,13444,0.057583,75215994,82019789,0.101694,True,0.483295
3,afafb1c3-90c4-4918-8910-3a2338a812c5,3878d999-6087-4a40-a59e-45abe8978736,437778,23,15,0.564485,292,1,False,0.271352,...,633556,37062,5290,245,0.927607,32759775,89513213,0.900505,False,21.686033
4,dcb1e68c-79ba-4808-bf74-d102fa68a526,4077faf8-bc0c-42df-b060-f90d074e8e01,4388903,3,30,0.556782,215,27,False,0.757624,...,55799,16634,5733,19235,0.723132,12315042,25073380,0.589176,True,46.046599

In [7]:
# Column names
print("\nColumns:")
print(df.columns.tolist())

# Data types
print("\nData Types:")
print(df.dtypes)

Columns:
['reel_id', 'creator_id', 'creator_followers', 'posting_time', 'reel_length_sec', 'hook_strength_score', 'caption_length', 'hashtags_count', 'trending_audio', 'audio_popularity_score', 'video_quality_score', 'editing_quality_score', 'avg_watch_time_sec', 'retention_rate', 'completion_rate', 'rewatch_rate', 'likes', 'comments', 'shares', 'saves', 'engagement_rate', 'impressions', 'reach', 'non_follower_reach_ratio', 'explore_page_boost', 'virality_score']

Data Types:
reel_id                      object
creator_id                   object
creator_followers             int64
posting_time                  int64
reel_length_sec               int64
hook_strength_score         float64
caption_length                int64
hashtags_count                int64
trending_audio                 bool
audio_popularity_score      float64
video_quality_score         float64
editing_quality_score       float64
avg_watch_time_sec          float64
retention_rate              float64
completion_rate             float64
rewatch_rate                float64
likes                         int64
comments                      int64
shares                        int64
saves                         int64
engagement_rate             float64
impressions                   int64
reach                         int64
non_follower_reach_ratio    float64
explore_page_boost             bool
virality_score              float64
dtype: object

In [9]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing %": (df.isnull().sum()/len(df))*100
})

missing_summary

                          Missing Values  Missing %
reel_id                                0        0.0
creator_id                             0        0.0
creator_followers                      0        0.0
posting_time                           0        0.0
reel_length_sec                        0        0.0
hook_strength_score                    0        0.0
caption_length                         0        0.0
hashtags_count                         0        0.0
trending_audio                         0        0.0
audio_popularity_score                 0        0.0
video_quality_score                    0        0.0
editing_quality_score                  0        0.0
avg_watch_time_sec                     0        0.0
retention_rate                         0        0.0
completion_rate                        0        0.0
rewatch_rate                           0        0.0
likes                                  0        0.0
comments                               0        0.0
shares                                 0        0.0
saves                                  0        0.0
engagement_rate                        0        0.0
impressions                            0        0.0
reach                                  0        0.0
non_follower_reach_ratio               0        0.0
explore_page_boost                     0        0.0
virality_score                         0        0.0

In [11]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [13]:
print("Number of Rows :", len(df))
print("Number of Columns :", df.shape[1])

print("Unique Reel IDs :", df['reel_id'].nunique())
print("Unique Creator IDs :", df['creator_id'].nunique())

Number of Rows : 100000
Number of Columns : 26
Unique Reel IDs : 100000
Unique Creator IDs : 100000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   reel_id                   100000 non-null  object
 1   creator_id                100000 non-null  object
 2   creator_followers         100000 non-null  int64
 3   posting_time              100000 non-null  int64
 4   reel_length_sec           100000 non-null  int64
 5   hook_strength_score       100000 non-null  float64
 6   caption_length            100000 non-null  int64
 7   hashtags_count            100000 non-null  int64
 8   trending_audio            100000 non-null  bool
 9   audio_popularity_score    100000 non-null  float64
 10  video_quality_score       100000 non-null  float64
 11  editing_quality_score     100000 non-null  float64
 12  avg_watch_time_sec        100000 non-null  float64
 13  retention_rate            100000 non-null  float64
 14  completion_rate           100000 non-null  float64
 15  rewatch_rate              100000 non-null  float64
 16  likes                     100000 non-null  int64
 17  comments                  100000 non-null  int64
 18  shares                    100000 non-null  int64
 19  saves                     100000 non-null  int64
 20  engagement_rate           100000 non-null  float64
 21  impressions               100000 non-null  int64
 22  reach                     100000 non-null  int64
 23  non_follower_reach_ratio  100000 non-null  float64
 24  explore_page_boost        100000 non-null  bool
 25  virality_score            100000 non-null  float64
dtypes: bool(2), float64(11), int64(11), object(2)
memory usage: 18.5+ MB

In [17]:
# Convert Boolean columns to 1 and 0
df['trending_audio'] = df['trending_audio'].astype(int)
df['explore_page_boost'] = df['explore_page_boost'].astype(int)

In [19]:
print(df[['trending_audio', 'explore_page_boost']].head())

   trending_audio  explore_page_boost
0               1                   0
1               0                   0
2               1                   1
3               0                   0
4               0                   1

In [21]:
# Create Original Virality Category using fixed score boundaries

df['original_virality_category'] = np.select(
    [
        df['virality_score'] <= 25,
        df['virality_score'] <= 50,
        df['virality_score'] <= 75
    ],
    [
        'Low',
        'Medium',
        'High'
    ],
    default='Viral'
)

In [23]:
df[['virality_score', 'original_virality_category']].head(10)

   virality_score original_virality_category
0       82.843160                      Viral
1       60.256519                       High
2        0.483295                        Low
3       21.686033                        Low
4       46.046599                     Medium
5       37.813178                     Medium
6       16.344602                        Low
7        2.737466                        Low
8       69.911861                       High
9       95.216318                      Viral

In [25]:
df['original_virality_category'].value_counts()

original_virality_category
Viral     25292
Medium    25027
Low       24896
High      24785
Name: count, dtype: int64

In [27]:
(
    df['original_virality_category']
      .value_counts(normalize=True)
      .mul(100)
      .round(2)
)

original_virality_category
Viral     25.29
Medium    25.03
Low       24.90
High      24.78
Name: proportion, dtype: float64

In [29]:
# Calculate 90th and 10th percentile thresholds
top_10_threshold = df['virality_score'].quantile(0.90)
bottom_10_threshold = df['virality_score'].quantile(0.10)

print(f"Top 10% Threshold: {top_10_threshold:.2f}")
print(f"Bottom 10% Threshold: {bottom_10_threshold:.2f}")

Top 10% Threshold: 90.21
Bottom 10% Threshold: 9.86

In [31]:
# Create Original Virality Group
df['original_virality_group'] = np.select(
    [
        df['virality_score'] >= top_10_threshold,
        df['virality_score'] <= bottom_10_threshold
    ],
    [
        'Top 10%',
        'Bottom 10%'
    ],
    default='Middle 80%'
)

In [33]:
df['original_virality_group'].value_counts()

original_virality_group
Middle 80%    80000
Bottom 10%    10000
Top 10%       10000
Name: count, dtype: int64

In [35]:
df[['virality_score', 'original_virality_group']].head(10)

   virality_score original_virality_group
0       82.843160              Middle 80%
1       60.256519              Middle 80%
2        0.483295              Bottom 10%
3       21.686033              Middle 80%
4       46.046599              Middle 80%
5       37.813178              Middle 80%
6       16.344602              Middle 80%
7        2.737466              Bottom 10%
8       69.911861              Middle 80%
9       95.216318                 Top 10%

In [37]:
# Columns used for Business Virality Index
bvi_columns = [
    'non_follower_reach_ratio',
    'shares',
    'engagement_rate',
    'saves',
    'reach',
    'impressions'
]

# Min-Max Normalization
for col in bvi_columns:
    df[col + '_norm'] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())

In [39]:
df[[col + '_norm' for col in bvi_columns]].head()

,non_follower_reach_ratio_norm,shares_norm,engagement_rate_norm,saves_norm,reach_norm,impressions_norm
0,0.960160,0.558033,0.884297,0.710167,0.390073,0.759681
1,0.909753,0.336500,0.609123,0.660067,0.841348,0.907223
2,0.101696,0.462767,0.057575,0.448133,0.820219,0.752157
3,0.900542,0.176333,0.927609,0.008167,0.895157,0.327581
4,0.589199,0.191100,0.723131,0.641167,0.250728,0.123127

In [41]:
for col in bvi_columns:
    print(f"{col}_norm")
    print("Min:", df[col + '_norm'].min())
    print("Max:", df[col + '_norm'].max())
    print("-"*30)

non_follower_reach_ratio_norm
Min: 0.0
Max: 1.0
------------------------------
shares_norm
Min: 0.0
Max: 1.0
------------------------------
engagement_rate_norm
Min: 0.0
Max: 1.0
------------------------------
saves_norm
Min: 0.0
Max: 1.0
------------------------------
reach_norm
Min: 0.0
Max: 1.0
------------------------------
impressions_norm
Min: 0.0
Max: 1.0
------------------------------

In [43]:
# Calculate Business Virality Index (BVI)

df['business_virality_index'] = (
    0.30 * df['non_follower_reach_ratio_norm'] +
    0.25 * df['shares_norm'] +
    0.20 * df['engagement_rate_norm'] +
    0.10 * df['saves_norm'] +
    0.10 * df['reach_norm'] +
    0.05 * df['impressions_norm']
) * 100

In [45]:
df[[
    'non_follower_reach_ratio_norm',
    'shares_norm',
    'engagement_rate_norm',
    'saves_norm',
    'reach_norm',
    'impressions_norm',
    'business_virality_index'
]].head()

,non_follower_reach_ratio_norm,shares_norm,engagement_rate_norm,saves_norm,reach_norm,impressions_norm,business_virality_index
0,0.960160,0.558033,0.884297,0.710167,0.390073,0.759681,75.242377
1,0.909753,0.336500,0.609123,0.660067,0.841348,0.907223,67.437824
2,0.101696,0.462767,0.057575,0.448133,0.820219,0.752157,32.215863
3,0.900542,0.176333,0.927609,0.008167,0.895157,0.327581,60.647896
4,0.589199,0.191100,0.723131,0.641167,0.250728,0.123127,46.450675

In [47]:
df['business_virality_index'].describe()

count    100000.000000
mean         50.013906
std          13.376842
min           4.483087
25%          40.614342
50%          50.042949
75%          59.444897
max          93.568134
Name: business_virality_index, dtype: float64

In [49]:
# Calculate Quartile Thresholds for BVI

q1 = df['business_virality_index'].quantile(0.25)
q2 = df['business_virality_index'].quantile(0.50)
q3 = df['business_virality_index'].quantile(0.75)

print(f"Q1 (25th Percentile): {q1:.2f}")
print(f"Q2 (50th Percentile): {q2:.2f}")
print(f"Q3 (75th Percentile): {q3:.2f}")

Q1 (25th Percentile): 40.61
Q2 (50th Percentile): 50.04
Q3 (75th Percentile): 59.44

In [51]:
# Create Business Virality Category using Quartiles

df['business_virality_category'] = np.select(
    [
        df['business_virality_index'] <= q1,
        df['business_virality_index'] <= q2,
        df['business_virality_index'] <= q3
    ],
    [
        'Low',
        'Medium',
        'High'
    ],
    default='Viral'
)

In [53]:
df[['business_virality_index', 'business_virality_category']].head(10)

   business_virality_index business_virality_category
0                75.242377                      Viral
1                67.437824                      Viral
2                32.215863                        Low
3                60.647896                      Viral
4                46.450675                     Medium
5                51.934959                       High
6                56.098549                       High
7                39.199603                        Low
8                38.521950                        Low
9                50.410909                       High

In [55]:
df['business_virality_category'].value_counts()

business_virality_category
Viral     25000
Low       25000
Medium    25000
High      25000
Name: count, dtype: int64

In [57]:
# Calculate the 90th and 10th percentile thresholds for BVI

bvi_top_10 = df['business_virality_index'].quantile(0.90)
bvi_bottom_10 = df['business_virality_index'].quantile(0.10)

print(f"Top 10% Threshold : {bvi_top_10:.2f}")
print(f"Bottom 10% Threshold : {bvi_bottom_10:.2f}")

Top 10% Threshold : 67.52
Bottom 10% Threshold : 32.42

In [59]:
# Create Business Virality Group

df['business_virality_group'] = np.select(
    [
        df['business_virality_index'] >= bvi_top_10,
        df['business_virality_index'] <= bvi_bottom_10
    ],
    [
        'Top 10%',
        'Bottom 10%'
    ],
    default='Middle 80%'
)

In [61]:
df[['business_virality_index', 'business_virality_group']].head(10)

   business_virality_index business_virality_group
0                75.242377                 Top 10%
1                67.437824              Middle 80%
2                32.215863              Bottom 10%
3                60.647896              Middle 80%
4                46.450675              Middle 80%
5                51.934959              Middle 80%
6                56.098549              Middle 80%
7                39.199603              Middle 80%
8                38.521950              Middle 80%
9                50.410909              Middle 80%

In [63]:
df['business_virality_group'].value_counts()

business_virality_group
Middle 80%    80000
Top 10%       10000
Bottom 10%    10000
Name: count, dtype: int64

In [65]:
# Store all important thresholds

thresholds = {
    "Original Virality Top 10%": top_10_threshold,
    "Original Virality Bottom 10%": bottom_10_threshold,
    "BVI Q1": q1,
    "BVI Median": q2,
    "BVI Q3": q3,
    "BVI Top 10%": bvi_top_10,
    "BVI Bottom 10%": bvi_bottom_10
}

for key, value in thresholds.items():
    print(f"{key}: {value:.2f}")

Original Virality Top 10%: 90.21
Original Virality Bottom 10%: 9.86
BVI Q1: 40.61
BVI Median: 50.04
BVI Q3: 59.44
BVI Top 10%: 67.52
BVI Bottom 10%: 32.42

In [67]:
# Export the final dataset
df.to_excel("Instagram_Reels_BVI_Final_Dataset.xlsx", index=False)

print("Dataset exported successfully!")

Dataset exported successfully!